Projekt_Sklep/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('items/', include("items.urls")),
    path('dasboard/', include('dashboard.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    path("", views.index, name="index"),
]

dashboard/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LogoutView
from .forms import LoginForm

app_name = 'dashboard'

urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("login/", auth_views.LoginView.as_view(template_name="login.html", authentication_form=LoginForm), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("orders/", views.orders, name="orders"),
    path("<int:pk>/switch_status/", views.switch_status, name="switch_status"),
]

items/urls.py
from django.urls import path
from . import views

app_name = 'items'

urlpatterns = [
    path("item_list/", views.item_list, name="item_list"),
    path("<int:pk>/", views.detail, name="detail"),
    path("<int:pk>/delete/", views.delete, name="delete"),
    path("<int:pk>/edit/", views.edit, name="edit"),
    path("new_item/", views.new_item, name="new_item"),
    path("new_wydawca/", views.new_wydawca, name="new_wydawca"),
    path("new_tematyka/", views.new_tematyka, name="new_tematyka"),
    path("<int:pk>/new_order/", views.new_order, name="new_order"),
    path("<int:pk>/item_list_category", views.item_list_category, name="item_list_category")
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render
from items.models import Produkt, Tematyka


# Create your views here.


def index(request):
    produkty = Produkt.objects.filter(ilosc__range=[1, 3]).order_by('?')[:3]
    teamty = Tematyka.objects.all()

    return render(request, "core/index.html", {
        "produkty": produkty,
        "tematy": teamty
    })

core/templates/core/base.html
<!DOCTYPE html>
<html lang="pl">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>{% block title %}{% endblock %}</title>
</head>

<body class="flex flex-col min-h-screen">
    <nav class="p-4 flex justify-between items-center border-b border-gray-500">
        <a href="/">
            <div class="flex items-center">
                <img src="{% static 'logo.png' %}" alt="logo" class="p-1">
                <span class="text-lg font-semibold">Szachownica</span>
            </div>
        </a>

        <div class="">
            {% if request.user.is_authenticated %}
                <span class="text-lg font-semibold text-green-600 px-4">Witaj {{ user.username }}</span>
            {% else %}
                <span class="text-lg font-semibold text-green-600 px-4">Witaj użytkowniku</span>
            {% endif %}

            <a href="{% url 'items:item_list' %}" class="p-3 text-lg font-semibold rounded-xl bg-gray-600 text-white hover:bg-gray-800">Produkty</a>

            {% if request.user.is_authenticated %}
                <a href="{% url 'dashboard:orders' %}" class="p-3 text-lg font-semibold rounded-xl bg-gray-600 text-white hover:bg-gray-800">Zamówienia</a>
            {% endif %}

            {% if request.user.is_authenticated %}
                <a href="{% url 'dashboard:logout' %}" class="p-3 text-lg font-semibold rounded-xl bg-gray-600 text-white hover:bg-gray-800">Wyloguj</a>
            {% else %}
                <a href="{% url 'dashboard:signup' %}" class="p-3 text-lg font-semibold rounded-xl bg-gray-600 text-white hover:bg-gray-800">Zarejestruj</a>
                <a href="{% url 'dashboard:login' %}" class="p-3 text-lg font-semibold rounded-xl bg-gray-600 text-white hover:bg-gray-800">Zaloguj</a>
            {% endif %}
        </div>
    </nav>

    <div>
        {% block content %}
        {% endblock %}
    </div>

    <footer class="p-4 flex w-screen mt-auto justify-between bg-gray-800">
        <div class="w-2/3 pr-10">
            <h3 class="mb-5 font-semibold text-gray-400">O nas</h3>
            <p class="text-lg text-gray-500">Projekt BD<br>Filip Juchnowicz<br>Bartłomiej Gościniak</p>
        </div>

        <div class="w-1/3">
            <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>
            <ul>
                <li><a href="#" class="text-lg text-teal-400 hover:text-teal-700">Kontakt</a></li>
            </ul>
        </div>
    </footer>
</body>
</html>

core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}
    Szachownica
{% endblock %}

{% block content %}
    <div class="m-4 px-5 py-10 bg-gray-300 rounded-xl">
        <h2 class="mb-10 text-2xl text-center font-semibold">Ostatnie sztuki!</h2>

        <div class="grid grid-cols-3 gap-2">
            {% for produkt in produkty %}
                <a href="{% url 'items:detail' produkt.id %}" class="flex items-center bg-white rounded-r-xl">
                    <div class="w-2/4">
                        <img src="{{ produkt.zdjecie.url }}" class="w-full h-full object-contain" alt="produkt_img">
                    </div>

                    <div class="border-l-2 border-solid border-black h-full mr-1"></div>

                    <div class="p-6 w-2/4">
                        <h2 class="text-2xl">{{ produkt.nazwa }}</h2>
                        <p class="text-gray-500">Cena: {{ produkt.cena }} zł</p>
                        <p class="text-gray-500">Wiek: {{ produkt.wiek }}+</p>
                        <p class="text-gray-500">{{ produkt.tematyka }}</p>
                    </div>
                </a>
            {% endfor %}
        </div>
    </div>

    <div class="m-4 px-5 py-10 bg-gray-300 rounded-xl">
        <h2 class="mb-10 text-2xl text-center font-semibold">Kategorie</h2>

        {% for temat in tematy %}
            <a href="{% url 'items:item_list_category' temat.id %}" class="inline mx-2 p-4 bg-white rounded-xl font-semibold text-4xl border-solid border-2 border-black">
                {{ temat }}
            </a>
        {% endfor %}
    </div>
{% endblock %}