Projekt_Sklep/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('items/', include("items.urls")),
    path('dasboard/', include('dashboard.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    path("", views.index, name="index"),
]

items/urls.py
from django.urls import path
from . import views

app_name = 'items'

urlpatterns = [
    path("item_list/", views.item_list, name="item_list"),
    path("<int:pk>/", views.detail, name="detail"),
    path("<int:pk>/delete/", views.delete, name="delete"),
    path("<int:pk>/edit/", views.edit, name="edit"),
    path("new_item/", views.new_item, name="new_item"),
    path("new_wydawca/", views.new_wydawca, name="new_wydawca"),
    path("new_tematyka/", views.new_tematyka, name="new_tematyka"),
    path("<int:pk>/new_order/", views.new_order, name="new_order"),
    path("<int:pk>/item_list_category", views.item_list_category, name="item_list_category")
]

items/models.py
from django.db import models
# Create your models here.


class Wydawca(models.Model):
    nazwa = models.CharField(max_length=255)
    mail = models.CharField(max_length=255)
    adres = models.CharField(max_length=255)

    class Meta:
        ordering = ('nazwa',)
        verbose_name_plural = 'Wydawcy'

    def __str__(self):
        return self.nazwa


class Tematyka(models.Model):
    temat = models.CharField(max_length=255)

    class Meta:
        verbose_name_plural = "Tematyki"


    def __str__(self):
        return self.temat


class Produkt(models.Model):
    nazwa = models.CharField(max_length=255)
    zdjecie = models.ImageField(upload_to="zdj_produktow", blank=True, null=False)
    wydawca = models.ForeignKey(Wydawca, related_name="produkty", on_delete=models.CASCADE)
    ilosc = models.IntegerField()
    cena = models.FloatField()
    wiek = models.IntegerField()
    tematyka = models.ForeignKey(Tematyka, related_name="teamtyka", on_delete=models.CASCADE)
    trudnosc = models.CharField(max_length=255)

    class Meta:
        ordering = ("nazwa",)
        verbose_name_plural = "Produkty"

    def __str__(self):
        return self.nazwa

items/forms.py
from django import forms
from .models import Wydawca, Produkt, Tematyka


def get_wydawca_list():
    wydawca = Wydawca.objects.values_list("nazwa", flat=True)
    return [[".*", "--------"]] + [[x, x] for x in wydawca]


class FilterForm(forms.Form):
    class Meta:
        fields = ("sortowanie",)

    sortowanie = forms.ChoiceField(choices=(
        ("nazwa", "A-Z"), ("-nazwa", "Z-A"),
        ("wiek", "Wiek, rosnąco"), ("-wiek", "Wiek, malejąco"),
        ("ilosc", "Ilość, rosnąco"), ("-ilosc", "Ilość, malejąco")), widget=forms.Select(attrs={
            "class": "w-full py-2 px-3 my-2 rounded-xl"
        })
    )

    wydawca = forms.ChoiceField(choices=get_wydawca_list(), widget=forms.Select(attrs={
            "class": "w-full py-2 px-3 my-2 rounded-xl"
        }))

    ilosc_min = forms.IntegerField(widget=forms.NumberInput(attrs={
        "class": "w-1/3 py-2 px-1 my-2 rounded-xl"
    }), initial=0)
    ilosc_max = forms.IntegerField(widget=forms.NumberInput(attrs={
        "class": "w-1/3 py-2 px-1 my-2 rounded-xl"
    }), initial=500)

    cena_min = forms.FloatField(widget=forms.NumberInput(attrs={
        "class": "w-1/3 py-2 px-1 my-2 rounded-xl"
    }), initial=0)
    cena_max = forms.FloatField(widget=forms.NumberInput(attrs={
        "class": "w-1/3 py-2 px-1 my-2 rounded-xl"
    }), initial=500)

    wiek_min = forms.IntegerField(widget=forms.NumberInput(attrs={
        "class": "w-1/3 py-2 px-1 my-2 rounded-xl"
    }), initial=0)
    wiek_max = forms.IntegerField(widget=forms.NumberInput(attrs={
        "class": "w-1/3 py-2 px-1 my-2 rounded-xl"
    }), initial=500)


INPUT_CLASSES = "w-full py-4 px-6 rounded-xl border"


class EditItemForm(forms.ModelForm):
    class Meta:
        model = Produkt
        fields = ("nazwa", "zdjecie", "wydawca", "ilosc", "cena", "wiek", "tematyka", "trudnosc")

        widgets = {
            "nazwa": forms.TextInput(attrs={
                "class": INPUT_CLASSES
            }),
            "zdjecie": forms.FileInput(attrs={
                "class": INPUT_CLASSES,
                # "required": True
            }),
            "wydawca": forms.RadioSelect(attrs={
                "class": "rounded-xl border"
            }),
            "ilosc": forms.NumberInput(attrs={
                "class": INPUT_CLASSES
            }),
            "cena": forms.NumberInput(attrs={
                "class": INPUT_CLASSES
            }),
            "wiek": forms.NumberInput(attrs={
                "class": INPUT_CLASSES
            }),
            "tematyka": forms.RadioSelect(attrs={
                "class": "rounded-xl border"
            }),
            "trudnosc": forms.TextInput(attrs={
                "class": INPUT_CLASSES
            })
        }


class NewItemForm(forms.ModelForm):
    class Meta:
        model = Produkt
        fields = ("nazwa", "zdjecie", "wydawca", "ilosc", "cena", "wiek", "tematyka", "trudnosc")

        widgets = {
            "nazwa": forms.TextInput(attrs={
                "class": INPUT_CLASSES
            }),
            "zdjecie": forms.FileInput(attrs={
                "class": INPUT_CLASSES,
                "required": True
            }),
            "wydawca": forms.RadioSelect(attrs={
                "class": "rounded-xl border"
            }),
            "ilosc": forms.NumberInput(attrs={
                "class": INPUT_CLASSES
            }),
            "cena": forms.NumberInput(attrs={
                "class": INPUT_CLASSES
            }),
            "wiek": forms.NumberInput(attrs={
                "class": INPUT_CLASSES
            }),
            "tematyka": forms.RadioSelect(attrs={
                "class": "rounded-xl border"
            }),
            "trudnosc": forms.TextInput(attrs={
                "class": INPUT_CLASSES
            })
        }


class NewWydawcaForm(forms.ModelForm):
    class Meta:
        model = Wydawca
        fields = ("nazwa", "mail", "adres")

        widgets = {
            "nazwa": forms.TextInput(attrs={
                "class": INPUT_CLASSES
            }),
            "mail": forms.TextInput(attrs={
                "class": INPUT_CLASSES
            }),
            "adres": forms.TextInput(attrs={
                "class": INPUT_CLASSES
            }),
        }


class NewTematykaForm(forms.ModelForm):
    class Meta:
        model = Tematyka
        fields = ("temat",)

        widgets = {
            "temat": forms.TextInput(attrs={
                "class": INPUT_CLASSES
            })
        }

items/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
import dashboard.models
from dashboard.models import Stan
from dashboard.views import orders
from .models import Produkt
from .forms import FilterForm, EditItemForm, NewItemForm, NewWydawcaForm, NewTematykaForm


# Create your views here.


def item_list(request):
    if request.method == "POST":
        form = FilterForm(request.POST)
        produkty = Produkt.objects.filter(
            wydawca__nazwa__regex=form.data["wydawca"],
            ilosc__range=[form.data["ilosc_min"], form.data["ilosc_max"]],
            cena__range=[form.data["cena_min"], form.data["cena_max"]],
            wiek__range=[form.data["wiek_min"], form.data["wiek_max"]],
        ).order_by(form.data["sortowanie"])

    else:
        form = FilterForm()
        produkty = Produkt.objects.all()

    return render(request, "item_list.html", {
        "form": form,
        "produkty": produkty
    })


def item_list_category(request, pk):
    form = FilterForm()
    produkty = Produkt.objects.filter(tematyka=pk)

    return render(request, "item_list.html", {
        "form": form,
        "produkty": produkty
    })


def detail(request, pk):
    produkt = get_object_or_404(Produkt, pk=pk)
    random_produkty = Produkt.objects.filter(tematyka=produkt.tematyka, pk=not pk).order_by('?')[:3]

    return render(request, "detail.html", {
        "produkt": produkt,
        "random_produkty": random_produkty
    })


@login_required
def delete(request, pk):
    produkt = get_object_or_404(Produkt, pk=pk)
    produkt.delete()

    return redirect("items:item_list")


@login_required
def edit(request, pk):
    produkt = get_object_or_404(Produkt, pk=pk)

    if request.method == "POST":
        form = EditItemForm(request.POST, request.FILES, instance=produkt)

        if form.is_valid():
            form.save()
            return redirect("items:detail", pk=produkt.id)
    else:
        form = EditItemForm(instance=produkt)

    return render(request, "form.html", {
        "form": form,
        "title": "Edycja produktu"
    })


@login_required()
def new_item(requset):
    if requset.method == "POST":
        form = NewItemForm(requset.POST, requset.FILES)

        if form.is_valid():
            produkt = form.save()

        return redirect("items:detail", pk=produkt.id)
    else:
        form = NewItemForm()

    return render(requset, "form.html", {
        "form": form,
        "title": "Utwórz nowy produkt"
    })


@login_required()
def new_wydawca(requset):
    if requset.method == "POST":
        form = NewWydawcaForm(requset.POST)

        if form.is_valid():
            form.save()

        return redirect("items:item_list")
    else:
        form = NewWydawcaForm()

    return render(requset, "form.html", {
        "form": form,
        "title": "Utwórz nowego wydawcę"
    })


@login_required()
def new_tematyka(request):
    if request.method == "POST":
        form = NewTematykaForm(request.POST)

        if form.is_valid():
            form.save()

        return redirect("items:item_list")
    else:
        form = NewTematykaForm()

    return render(request, "form.html", {
        "form": form,
        "title": "Utwórz nową tematykę"
    })


@login_required()
def new_order(request, pk):
    produkt = Produkt.objects.get(pk=pk)
    produkt_ilosc = produkt.ilosc
    stan = Stan.objects.get(pk=1)

    if produkt_ilosc > 0:
        produkt_ilosc = produkt_ilosc - 1

        produkt.ilosc = produkt_ilosc
        order = dashboard.models.Zamowienia(produkt=produkt, stan_zamowienia=stan, uzytkownik=request.user)

        order.save()
        produkt.save()

    return detail(request, pk)

items/templates/detail.html
{% extends "core/base.html" %}

{% block title %}{{ item.name }}{% endblock %}

{% block content %}
    <div class="p-5 m-5 rounded-xl flex bg-gray-200 h-2/4 w-3/4 mx-auto">
        <div class="w-1/3">
            <img src="{{ produkt.zdjecie.url }}" class="h-full w-full object-contain border-2 border-solid border-black">
        </div>

        <div class="p-6 w-2/3">
            <h2 class="text-4xl mb-4">{{ produkt.nazwa }}</h2>
            <div class="text-2xl">
                <p class="text-gray-500">Cena: {{ produkt.cena }} zł</p>
                <p class="text-gray-500">Wiek: {{ produkt.wiek }}+</p>
                <p class="text-gray-500">{{ produkt.tematyka }}</p>
                <p class="text-gray-500">Ilość: {{ produkt.ilosc }}</p>
                <p class="text-gray-500">Wydawca: {{ produkt.wydawca }}</p>
                <p class="text-gray-500">Poziom trudności: {{ produkt.trudnosc }}</p>
            </div>

            {% if request.user.is_admin %}
                <div class="p-5 m-2 bg-gray-400 rounded-xl">
                    <h1 class="font-semibold">Panel administracyjny</h1>
                    <a href="{% url 'items:edit' produkt.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-gray-600 text-white rounded-xl">Edytuj</a>
                    <a href="{% url 'items:delete' produkt.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl">Usuń</a>
                </div>
            {% endif %}

            {% if not request.user.is_admin and request.user.is_authenticated %}
                <div class="p-5 m-2 bg-gray-400 rounded-xl">
                    <h1 class="font-semibold">Panel klienta</h1>
                    <a href="{% url 'items:new_order' produkt.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-green-500 text-white rounded-xl">Zamów</a>
                </div>
            {% endif %}
        </div>
    </div>

        {% if random_produkty.count > 0 %}
            <div class="m-4 px-5 py-10 bg-gray-300 rounded-xl">
                <h2 class="mb-10 text-2xl text-center font-semibold">Podobne produkty</h2>

                <div class="grid grid-cols-3 gap-2">
                    {% for random_produkt in random_produkty %}
                        <a href="{% url 'items:detail' random_produkt.id %}" class="flex items-center bg-white rounded-r-xl">
                            <div class="w-2/4">
                                <img src="{{ random_produkt.zdjecie.url }}" class="w-full h-full object-contain" alt="produkt_img">
                            </div>

                            <div class="border-l-2 border-solid border-black h-full mr-1"></div>

                            <div class="p-6 w-2/4">
                                <h2 class="text-2xl">{{ random_produkt.nazwa }}</h2>
                                <p class="text-gray-500">Cena: {{ random_produkt.cena }} zł</p>
                                <p class="text-gray-500">Wiek: {{ random_produkt.wiek }}+</p>
                                <p class="text-gray-500">{{ random_produkt.tematyka }}</p>
                            </div>
                        </a>
                    {% endfor %}
                </div>
        {% endif %}
    </div>
{% endblock %}

items/templates/form.html
{% extends "core/base.html" %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <h1 class="mb-6 text-3xl">{{ title }}</h1>

    <form method="post" action="." enctype="multipart/form-data" class="p-10 m-4 bg-gray-300 rounded-xl">
        {% csrf_token %}

        <div class="space-y-4">
            {{ form.as_p }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button type="submit" class="mt-4 py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Zatwierdź</button>
    </form>
{% endblock %}

items/templates/item_list.html
{% extends "core/base.html" %}

{% block title %}Lista produktów{% endblock %}

{% block content %}
    <div class="px-2 py-6 m-6 bg-gray-300 rounded-xl flex">
        <div class="bg-gray-400 p-2 mx-2 rounded-xl w-1/5 sticky top-5 h-1/2">
            {% if request.user.is_admin %}
                <div class="p-2 m-2 bg-gray-200 rounded-xl">
                    <p class="text-lg font-semibold mb-3">Panel administracyjny</p>
                    <hr>
                    <a href="{% url 'items:new_item' %}" class="p-1 w-full inline-block bg-green-400 my-1 hover:bg-green-600 font-semibold text-lg rounded-xl text-center">Utwórz nowy produkt</a>
                    <a href="{% url 'items:new_wydawca' %}" class="p-1 w-full inline-block bg-green-400 my-1 hover:bg-green-600 font-semibold text-lg rounded-xl text-center">Utwórz nowego wydawce</a>
                    <a href="{% url 'items:new_tematyka' %}" class="p-1 w-full inline-block bg-green-400 my-1 hover:bg-green-600 font-semibold text-lg rounded-xl text-center">Utwórz nową teamtykę</a>
                </div>
            {% endif %}

            <form action="." method="POST">
                {% csrf_token %}

                <div class="mb-2">
                    <label class="inline-block mb-1 font-semibold text-2xl">Sortowanie</label>
                    {{ form.sortowanie }}
                </div>

                <div>
                    <p class="inline-block mb-1 font-semibold text-2xl">Filtrowanie</p><br>

                    <div>
                        <label class="inline-block mb-1 font-semibold">Wydawca</label><br>
                        {{ form.wydawca }}
                    </div>

                    <div>
                        <label class="inline-block mb-1 font-semibold">Ilość</label><br>
                        Od {{ form.ilosc_min }} do {{ form.ilosc_max }}
                    </div>

                    <div>
                        <label class="inline-block mb-1 font-semibold">Cena</label><br>
                        Od {{ form.cena_min }} do {{ form.cena_max }}
                    </div>

                    <div>
                        <label class="inline-block mb-1 font-semibold">Wiek</label><br>
                        Od {{ form.wiek_min }} do {{ form.wiek_max }}
                    </div>
                </div>

                <div class="w-full flex">
                    <button type="submit" class="p-2 my-2 mr-1 w-1/2 bg-green-600 hover:bg-green-800 font-semibold text-lg rounded-xl flex">Filtruj/Sortuj</button>
                    <a href="{% url 'items:item_list' %}" class="p-2 my-2 ml-auto w-1/2 bg-red-600 hover:bg-red-800 font-semibold text-lg rounded-xl flex">Reset</a>
                </div>
            </form>
        </div>

        <div class="w-4/5 grid grid-cols-2 max-[1000px]:grid-cols-1 gap-5">
            {% for produkt in produkty %}
                <a href="{% url 'items:detail' produkt.id %}" class="flex items-center bg-white rounded-r-xl">
                        <div class="w-2/5 border-solid border-2 border-black">
                            <img src="{{ produkt.zdjecie.url }}" alt="produkt_img" class="h-full w-full object-contain">
                        </div>

                        <div class="p-6 w-3/5">
                            <h2 class="text-4xl mb-2">{{ produkt.nazwa }}</h2>

                            <div class="float-left mr-6 text-xl text-gray-500">
                                <p class="py-1">Cena: {{ produkt.cena }} zł</p>
                                <p class="py-1">Wiek: {{ produkt.wiek }}+</p>
                                <p class="py-1">{{ produkt.tematyka }}</p>
                            </div>

                            <div class="text-xl text-gray-500">
                                <p class="py-1">Ilość: {{ produkt.ilosc }}</p>
                                <p class="py-1">Wydawca: {{ produkt.wydawca }}</p>
                                <p class="py-1">Trudność: {{ produkt.trudnosc }}</p>
                            </div>
                        </div>
                </a>
            {% endfor %}
        </div>
    </div>
{% endblock %}