Projekt_Sklep/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('items/', include("items.urls")),
    path('dasboard/', include('dashboard.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    path("", views.index, name="index"),
]

dashboard/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LogoutView
from .forms import LoginForm

app_name = 'dashboard'

urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("login/", auth_views.LoginView.as_view(template_name="login.html", authentication_form=LoginForm), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("orders/", views.orders, name="orders"),
    path("<int:pk>/switch_status/", views.switch_status, name="switch_status"),
]

dashboard/models.py
import uuid

from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.


class Uzytkownik(AbstractUser):
    username = models.CharField(max_length=255, unique=True)
    email = models.CharField(max_length=255)
    password = models.CharField(max_length=255)
    is_admin = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = "Uzytkownicy"

    def __str__(self):
        return self.username


class Stan(models.Model):
    stan_zamowienia = models.CharField(max_length=30, null=False)

    class Meta:
        verbose_name_plural = "Stany"


    def __str__(self):
        return self.stan_zamowienia


class Zamowienia(models.Model):
    order_id = models.CharField(max_length=100, unique=True, default=uuid.uuid4)
    produkt = models.ForeignKey('items.Produkt', related_name="produkt", on_delete=models.CASCADE)
    stan_zamowienia = models.ForeignKey(Stan, related_name="order_state", on_delete=models.CASCADE)
    uzytkownik = models.ForeignKey(Uzytkownik, related_name="usernames", on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = "Zamówienia"

    def __str__(self):
        return self.order_id

dashboard/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import Uzytkownik, Zamowienia


class SignUpForm(UserCreationForm):
    class Meta:
        model = Uzytkownik
        fields = ("username", "email", "password1", "password2")

    username = forms.CharField(widget=forms.TextInput(attrs={
        "placeholder": "Nazwa użytkownika",
        "class": "w-full py-4 px-6 rounded-xl"
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        "placeholder": "Adres email",
        "class": "w-full py-4 px-6 rounded-xl",
        # "requiered": True
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        "placeholder": "Hasło",
        "class": "w-full py-4 px-6 rounded-xl"
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        "placeholder": "Powtórz hasło",
        "class": "w-full py-4 px-6 rounded-xl"
    }))


class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        "placeholder": "Nazwa użytkownika",
        "class": "w-full py-4 px-6 rounded-xl"
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        "placeholder": "Hasło",
        "class": "w-full py-4 px-6 rounded-xl"
    }))


class SwitchStatesForm(forms.ModelForm):
    class Meta:
        model = Zamowienia
        fields = ("stan_zamowienia",)

        widgets = {
            "stan": forms.RadioSelect(attrs={
                "class": "rounded-xl border"
            }
        )}

dashboard/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from .forms import SignUpForm, SwitchStatesForm
from .models import Zamowienia, Stan


# Create your views here.


def signup(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect("dashboard:login")
    else:
        form = SignUpForm()

    return render(request, "signup.html", {
        "form": form
    })


def logout(request):
    logout(request)


def orders(request):
    if request.user.is_admin:
        orders = Zamowienia.objects.all()
    else:
        orders = Zamowienia.objects.filter(uzytkownik=request.user.pk)

    form = SwitchStatesForm()

    return render(request, "zamowienia.html", context={
        "orders": orders,
        "form": form
    })


@login_required
def switch_status(request, pk):
    if request.method == "POST":
        order = get_object_or_404(Zamowienia, pk=pk)

        form_result = SwitchStatesForm(request.POST)
        order.stan_zamowienia = Stan.objects.get(pk=form_result["stan_zamowienia"].value())

        order.save()

    return redirect("dashboard:orders")

dashboard/templates/login.html
{% extends "core/base.html" %}

{% block title %}Logowanie{% endblock %}

{% block content %}
    <div class="w-1/2 p-6 my-4 mx-auto bg-gray-200 rounded-xl">
        <h1 class="mb-6 text-3xl">Zaloguj się</h1>
        <form method="post" action=".">
            {% csrf_token %}

            <div class="mb-3">
                <label class="inline-block mb-2">Nazwa użytkownika:</label><br>
                {{ form.username }}
            </div>

            <div class="mb-3">
                <label class="inline-block mb-2">Powtórz hasło:</label><br>
                {{ form.password }}
            </div>

            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-6 bg-red-100 rounded-xl">
                    {% for field in form %}
                        {{ field.errors }}
                    {% endfor %}

                    {{ form.non_field_errors }}
                </div>
            {% endif %}

            <button type="submit" class="py-4 mt-4 px-8 text-lg bg-green-400 hover:bg-green-700 rounded-xl text-white">Zarejestruj</button>
        </form>
    </div>
{% endblock %}

dashboard/templates/signup.html
{% extends "core/base.html" %}

{% block title %}Rejestracja{% endblock %}

{% block content %}
    <div class="w-1/2 p-6 my-4 mx-auto bg-gray-200 rounded-xl">
        <h1 class="mb-6 text-3xl">Zarejestruj się</h1>
        <form method="post" action=".">
            {% csrf_token %}

            <div class="mb-3">
                <label class="inline-block mb-2">Nazwa użytkownika:</label><br>
                {{ form.username }}
            </div>

            <div class="mb-3">
                <label class="inline-block mb-2">Email:</label><br>
                {{ form.email }}
            </div>

            <div class="mb-3">
                <label class="inline-block mb-2">Hasło:</label><br>
                {{ form.password1 }}
            </div>

            <div class="mb-3">
                <label class="inline-block mb-2">Powtórz hasło:</label><br>
                {{ form.password2 }}
            </div>

            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-6 bg-red-100 rounded-xl">
                    {% for field in form %}
                        {{ field.errors }}
                    {% endfor %}

                    {{ form.non_field_errors }}
                </div>
            {% endif %}

            <button type="submit" class="py-4 mt-4 px-8 text-lg bg-green-400 hover:bg-green-700 rounded-xl text-white">Zarejestruj</button>
        </form>
    </div>
{% endblock %}

dashboard/templates/zamowienia.html
{% extends "core/base.html" %}

{% block title %}Lista produktów{% endblock %}

{% block content %}
    <div class="px-2 py-6 m-6 bg-gray-200 rounded-xl flex items-center">
        <div class="w-full grid grid-cols-2 max-[1000px]:grid-cols-1 gap-2">
            {% for order in orders %}
                <div>
                    <div class="flex items-center mb-4 mx-5 bg-white rounded-r-xl h-full">
                        <div class="w-2/5">
                            <img src="{{ order.produkt.zdjecie.url }}" alt="produkt_img" class="h-full w-full object-contain">
                        </div>

                        <div class="p-6 w-4/5">
                            {% if request.user.is_admin %}
                                <h2 class="text-2xl font-semibold">{{ order.uzytkownik }}</h2>
                            {% endif %}

                            <h2 class="text-lg font-semibold">{{ order.order_id }}</h2>
                            <h3 class="text-2xl">{{ order.produkt.nazwa }}</h3>
                            <p class="font-semibold">Stan zamówienia: {{ order.stan_zamowienia }}</p>
                            <p class="text-gray-500">Cena: {{ order.produkt.cena }} zł</p>

                            {% if request.user.is_admin %}
                                <div class="p-2 m-2 border-solid border-2 border-black">
                                    <form action="{% url 'dashboard:switch_status' order.pk %}" method="POST">
                                        {% csrf_token %}

                                        {{ form.as_p }}

                                        <button type="submit" class="p-2 font-semibold bg-red-500 rounded-xl mt-3">Zmień status</button>
                                    </form>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}